services:
    api-phutran:
      container_name: api-phutran
      image: api-phutran
      environment:
        POSTGRES_HOST: postgres
        POSTGRES_PORT: ${POSTGRES_PORT}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
        JWT_SECRET: ${JWT_SECRET}
        PORT: ${PORT}
        NODE_ENV: ${NODE_ENV}
      build:
        context: .
        dockerfile: apps/api-phutran/Dockerfile
        
      ports:
        - "${PORT}:${PORT}"
      networks:
        - database-network
      depends_on:
        - postgres
      restart: unless-stopped

    postgres:
      container_name: postgres
      image: postgres:13.18
      ports:
        - "${POSTGRES_PORT}:${POSTGRES_PORT}"
      volumes:
        - postgres_data:/var/lib/postgresql/data
      networks:
        - database-network
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
      mem_limit: 1g
      cpus: 0.5
      restart: unless-stopped

networks:
  database-network: {}

volumes:
  postgres_data: {}